name: Process Icons

on:
    push:
        paths:
            - .github/**
            - original-images/**
            - original-svgs/**
            - process-icons.sh
    pull_request:
        paths:
            - .github/**
            - original-images/**
            - original-svgs/**
            - process-icons.sh
    workflow_dispatch:

permissions:
    contents: write

jobs:
    process_icons:
        name: Process Icons
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0  # Allows git diff to work properly

            - name: Setup ImageMagick
              uses: mfinelli/setup-imagemagick@v6

            - name: Make script executable
              run: chmod +x process-icons.sh

            - name: Run image resizing script
              run: ./process-icons.sh
