name: Resize PNG Images

on:
    push:
        paths:
            - .github/**
            - original-images/**
            - svgs/**
            - resize-images.sh
    pull_request:
        paths:
            - .github/**
            - original-images/**
            - svgs/**
            - resize-images.sh
    workflow_dispatch:

permissions:
    contents: write

jobs:
    resize_images:
        name: Resize PNG Images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0  # Allows git diff to work properly

            - name: Install ImageMagick
              run: sudo apt-get update && sudo apt-get install -y imagemagick

            - name: Make script executable
              run: chmod +x resize-images.sh

            - name: Run image resizing script
              run: ./resize-images.sh
