name: Resize PNG Images

on:
    push:
        paths:
            - .github/**
            - original-images/**
            - svgs/**
            - resize-images.sh
    pull_request:
        paths:
            - .github/**
            - original-images/**
            - svgs/**
            - resize-images.sh
    workflow_dispatch:

permissions:
    contents: write

jobs:
    resize_images:
        name: Resize PNG Images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0  # Allows git diff to work properly

            - name: Install ImageMagick
              run: sudo apt-get update && sudo apt-get install -y imagemagick

            - name: Make script executable
              run: chmod +x resize-images.sh

            - name: Run image resizing script
              run: ./resize-images.sh

            - name: Commit and push changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add ./icons
                  git commit -m 'Update icons'
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
